server:
  type: simple
  applicationContextPath: /
database:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/rest
  user: root
  password: 12345678
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true